### ISSUE TITLE
Apple Touch Icon

### ISSUE THREAD

**Issue by steveh259** [steveh259/website#1]
<p>Add an Apple Touch Icon to the website.</p>
<hr>
<p align="center"><b>DEV-INFO</b></p>

> <link rel="shortcut icon" href="/page/tpl/assets/images/favicon.ico">
	<link rel="apple-touch-icon" href="">
	<link rel="apple-touch-icon" sizes="72x72" href="">
	<link rel="apple-touch-icon" sizes="114x114" href="">

**Comment by ScrummerLP** [comment]
Voilà: [http://web-stuebchen.de/](http://web-stuebchen.de/)
Ein Generator für alles.
